logging:
  level:
    ROOT: INFO
    br.com.cactusdigital.erp.security: DEBUG
    org.springframework.security: trace
      
    
server:
  port: 9999

spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      org.hibernate.envers.revision_field_name: ID_REVI
      org.hibernate.envers.revision_type_field_name: ST_REVI
      org.hibernate.envers.store_data_at_delete: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/cd_security?useSSL=false
    username: root
    password: jesuscristo
    hikari:
      minimum-idle: 5
      # NUMERO MAXIMO DO POOL DE CONEXAO
      maximum-pool-size: 100
      idle-timeout: 60000
      pool-name: cadastrosCP
      # CONFIGURANDO PARA 60 SEG
      connection-timeout: 120000
      max-lifetime: 2000000
      data-source-properties:
        cache-prep-stmts: true
        prep-stmp-cache-size: 250
        prep-stmt-cache-sql-limit: 2048
        use-server-prep-stmts: true

  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: false
  profiles:
    active: native
  messages:
    basename: i18n/messages
     
#management:
#  endpoints:
#    web:
#      exposure:
#        include: ["health","info"]
#  endpoint:
#    auditevents:
#      enabled: true
#
#application: